# Production - PostgreSQL

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/medistock}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2230}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
