# Local development - PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/medistock
spring.datasource.username=postgres
spring.datasource.password=2230
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true